### ISSUE TITLE
Add plugins input

### ISSUE THREAD

**Issue by peterbandi** [py-actions/flake8#154]
Please add an input to specify a list of additional plugins (with versions) to install with pip for Flake8. For example `plugins: flake8-bugbear==22.1.11` as input would install the **flake8-bugbear** PyPI package version **22.1.11**.

**Comment by chrissimpkins** [comment]
Only need support for the pip install of the plugin package from PyPI?

**Comment by chrissimpkins** [comment]
Implemented.

Mind giving the [flake8-plugins](https://github.com/py-actions/flake8/tree/flake8-plugins) branch a try in your GH Action configuration?  

You should be able to configure it like this:

```yaml
- name: flake8 Lint
  uses: py-actions/flake8@flake8-plugins
  with:
    plugins: "flake8-bugbear==22.1.11"
```

If you need more than one plugin, use a space delimiter between packages.  Let me know if this works for you.
