### ISSUE TITLE
Action does not work with flake8 plugin 'pyproject-flake8'

### ISSUE THREAD

**Issue by jimisola** [py-actions/flake8#216]
I've tried to use this gh action with flake8 plugin 'pyproject-flake8' but it does not seem to work (commented out below). It does not pick up the configuration in pyproject.toml (e.g. max-lines).

It works however with a standard hatch run as exampled below.

```
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: pip install hatch pyproject-flake8
      - run: hatch run lint:flake8
      # - uses: py-actions/flake8@v2          
      #   with:
      #     plugins: "pyproject-flake8"
```
